### ISSUE TITLE
RFID RC522 related issue, no signal receive.

### ISSUE THREAD

**Issue by KanybekMomukeyev** [jdevelop/golang-rpi-extras#6]
Hi, thanks for sharing source codes.
Tried to run this code,  
```
// go version is: go1.10.1 linux/arm 
golang-rpi-extras/rf522/app/rf522_main.go 
```
on Raspberry Pi Mode 3, App started successfully, but not receiving any signal from rf522.

At the same tried python version of rf522 code, from 
```
https://github.com/mxgxw/MFRC522-python   
```
Every thing seems be ok.
Here the image, how i connected rf522:

<img width="650" alt="screen shot 2018-10-20 at 17 23 52" src="https://user-images.githubusercontent.com/866641/47255116-a3e57000-d48d-11e8-982f-6fd3de568134.png">

**Comment by jdevelop** [comment]
You didn't seem to connect the IRQ pin.

**Comment by jdevelop** [comment]
Can you give a shot to http://github.com/google/periph ? 

They use a different library for the interrupts, and I have ported the MFRC522 code for that framework.

Side note - I **never** tested this code with RPi 2 or 3, only Zero / ZeroW
